Repository dltxio/idem-mobile, pull requests merged in 2022-06, with the labels that each got.

#171 IDEM-143
  app/src/utils/formatters.ts
Labels: good first issue

#173 IDEM-172
  .github/workflows/ci.yml
  package.json
  yarn.lock
Labels: enhancement

#147 IDEM-147
  README.md
Labels: documentation

#195 Update README.md
  README.md
Labels: documentation
